### ISSUE TITLE
2015/2016 release?

### ISSUE THREAD

**Issue by ncouture** [mgedmin/irclog2html#14]
I see quite a few commits in 2015 but last release was in 2014. 

Since you're recommending installing with pip, would a release be appropriate at this time?

**Comment by mgedmin** [comment]
Whatever's on PyPI, I suppose.  Unless you want to beta-test the new incomplete WSGI-mode support, in which case you can run the git master and file bugs if you find any problems.

I wanted to get #10 done before I make a release, but got bogged down in the details.

**Comment by mgedmin** [comment]
irclog2html 2.15.0 is out on PyPI!
