### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by mapreri** [mgedmin/irclog2html#18]
Hi there :)

On [pypi](https://pypi.python.org/pypi/irclog2html) it's written:
```
    Licence: GPL v2 or later (http://www.gnu.org/copyleft/gpl.html)
```
But nowhere on the code I can see references neither to the "v2" nor to the "or later" part, which means that just according to the code the license would be [GPL-1](https://www.gnu.org/licenses/old-licenses/gpl-1.0.html) which is, erm, let's just say that I doubt you want it :)
Also the COPYING file reports the GPL-2 text.

Given that I think this is just a oversee, could you please specify on the various file headers the correct license under which this work is done?  (i.e. `GPL-2+` or `GPL v2 or later`, whatever unambiguous form you prefer)
While on it, be aware that also your copyright claim doesn't cover 2016, whilst you did some work on it.

For completeness, I want to say that what trigger this search of mine is my willingness to put this software in the Debian archive (just because 1) I'm using it since years 2) I'm a Debian Developer 3) I prefer installing software from the Debian archive instead of pypi or git checkouts).

**Comment by mgedmin** [comment]
Is the [notice in the README](https://github.com/mgedmin/irclog2html/blob/master/README.rst#misc) insufficient?

The comment `# Released under the terms of the GNU GPL` is lifted verbatim from [the original Perl version](https://github.com/mgedmin/irclog2html/blob/master/porting/irclog2html.pl) which was written by Jeff Waugh, and I'm not sure I have the right to change it.  Would you like to contact him for clarification?

**Comment by mgedmin** [comment]
(To clarify: irclog2html.py is a derived work of irclog2html.pl.  I made some chanes to the Perl script, found that rather painful and did a very literal translation to Python before refactoring everything.)

**Comment by mapreri** [comment]
I now wrote to him (using the email I found in the irclog2html.pl present on this repo).
I'll report as soon as I receive a reply (which I hope to receive…)

The notice in the README is actually a issue, as it's in direct conflict to what is stated on all the other files :(

> The comment # Released under the terms of the GNU GPL is lifted verbatim from the original Perl version which was written by Jeff Waugh, and I'm not sure I have the right to change it.

You don't have such a right, though I wonder if the heavy refactor operated since the rewrite is enough to say nothing is left of the original work (hence the original copyright holder doesn't hold anything anymore, and you can freely relicense the new work).  I've never quite understand at which point one can say so, and that's tricky land I usually prefer to stay away from.

**Comment by jdub** [comment]
Thanks for getting in touch, @mapreri. (Golly, I was a software freedom baby when I wrote that script!)

Two comments:

1. It was absolutely the intention of the author (me) and contributors that `irclog2html.pl` be released under terms of the GPL v2, being the canonical and uncontroversial version at the time. However,

2. I do not regard `irclog2html.py` to be a derivative work, and as far as copyright law allows, I release @mgedmin from any copyright obligations, real or perceived. 😄

**Comment by mgedmin** [comment]
Thanks!

I plan to make a new release soon.

**Comment by mapreri** [comment]
Oh, thank you all!

♥

**Comment by mgedmin** [comment]
irclog2html 2.15.2 is on pypi
