### ISSUE TITLE
parts of log message missing

### ISSUE THREAD

**Issue by lazka** [mgedmin/irclog2html#19]
``[14 Jan 12:37] <jsmith!n=jsmith@72.21.36.138> I'm going from A -> B``

results in 

``<tr id="t14 Jan 12:37"><th class="nick" style="background: #b15db1">jsmith</th><td class="text" style="color: #b15db1">B</td><td class="time"><a href="#t14 Jan 12:37" class="time">14 Jan 12:37</a></td></tr>``

i.e only "B" is shown in the message

one can reduce the test case to `[00:00:00] <!> -> X`

**Comment by mgedmin** [comment]
Thank you for a very clear bug report!

This is fixed in [2.15.3](https://pypi.python.org/pypi/irclog2html).

**Comment by lazka** [comment]
Thanks!

**Comment by mgedmin** [comment]
Note: to force irclog2html to generate incorrect old archives try something like

```sh
grep -l '>.*>' *.log | xargs touch
```
