### ISSUE TITLE
Github releases not matching those on PyPI

### ISSUE THREAD

**Issue by dregad** [mgedmin/irclog2html#28]
Just missing a few tags in the repo, I guess

- https://pypi.org/project/irclog2html/#history -> latest 2.17.2
- https://github.com/mgedmin/irclog2html/releases -> latest 2.16.0

**Comment by mgedmin** [comment]
My bad, I always forget that GitHub releases is a thing that exists.

Maybe I should just nuke them and leave PyPI as the sole source of truth?

**Comment by mgedmin** [comment]
Releases created for all the latest tags.

**Comment by dregad** [comment]
> Maybe I should just nuke them and leave PyPI as the sole source of truth?

I personally like to have them here, but it's your call 😉

> Releases created for all the latest tags.

Thanks!

**Comment by dregad** [comment]
Bump :wink:

**Comment by mgedmin** [comment]
Thank you.

The Makefile reminder didn't work at all :(
